apiVersion: v1
kind: Service
metadata:
  name: {{ include "recor-service.fullname" . }}
  namespace: recor
  labels:
    {{- include "recor-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ports.business }}
      targetPort: http
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "recor-service.selectorLabels" . | nindent 4 }}
