//! PostgreSQL adapter implementing `DeclarationRepository`.
//!
//! All write paths run a single transaction that:
//!   1. appends to `declaration_events` (the source of truth)
//!   2. upserts the `declarations` projection
//!   3. inserts a row into `outbox`
//!
//! Optimistic concurrency: the INSERT into `declaration_events` carries
//! `(declaration_id, aggregate_version)` UNIQUE. A version mismatch
//! surfaces as a unique-violation Postgres error and is translated to
//! `RepositoryError::Conflict`.
//!
//! Queries use the compile-time-checked `sqlx::query!` /
//! `sqlx::query_as!` macros (R-DECL-7). Type-checking happens at
//! `cargo build` time against the committed `.sqlx/` offline cache
//! (see `services/declaration/.sqlx/`). The cache is regenerated by
//! `cargo sqlx prepare --workspace` against a live Postgres with the
//! current `migrations/` applied; the runbook
//! `docs/runbooks/sqlx-cache-regeneration.md` explains when and how.
//! CI verifies the committed cache is fresh via
//! `cargo sqlx prepare --check --workspace`; production builds set
//! `SQLX_OFFLINE=true` so the build never reaches out to a database
//! (Doctrine 19: reproducible everything).

use async_trait::async_trait;
use serde_json::Value as JsonValue;
use sqlx::{PgPool, Postgres, Transaction};
use tracing::instrument;

use crate::application::port::{DeclarationRepository, RepositoryError};
use crate::application::DeclarationProjection;
use crate::domain::attestation::CryptographicAttestation;
use crate::domain::value_object::{
    BeneficialOwnerClaim, DeclarantRole, DeclarationId, DeclarationKind, DeclarationState,
    EntityId, VerificationLane,
};
use crate::domain::{
    DeclarationAmendedV1, DeclarationCorrectedV1, DeclarationEvent, DeclarationSubmittedV1,
    DeclarationSupersededV1, DeclarationVerifiedV1,
};

pub struct PostgresDeclarationRepository {
    pool: PgPool,
}

impl PostgresDeclarationRepository {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Run the bundled migrations against the database. Idempotent;
    /// safe to call on every service startup.
    pub async fn run_migrations(&self) -> Result<(), sqlx::migrate::MigrateError> {
        sqlx::migrate!("./migrations").run(&self.pool).await
    }
}

#[async_trait]
impl DeclarationRepository for PostgresDeclarationRepository {
    #[instrument(skip(self), fields(declaration_id = %id))]
    async fn load_events(
        &self,
        id: DeclarationId,
    ) -> Result<Vec<DeclarationEvent>, RepositoryError> {
        let rows = sqlx::query!(
            r#"
            SELECT event_type, event_payload
            FROM declaration_events
            WHERE declaration_id = $1
            ORDER BY aggregate_version ASC
            "#,
            id.0,
        )
        .fetch_all(&self.pool)
        .await?;

        rows.into_iter()
            .map(|row| decode_event(&row.event_type, row.event_payload))
            .collect()
    }

    #[instrument(skip(self, event), fields(
        declaration_id = %event.declaration_id(),
        event_type = event.event_type(),
        expected_version = expected_version,
    ))]
    async fn save_event(
        &self,
        event: &DeclarationEvent,
        expected_version: u64,
    ) -> Result<(), RepositoryError> {
        let mut tx = self.pool.begin().await?;
        let new_version =
            i64::try_from(expected_version.saturating_add(1)).unwrap_or(i64::MAX);

        insert_event(&mut tx, event, new_version).await?;
        upsert_projection(&mut tx, event, new_version).await?;
        write_outbox(&mut tx, event).await?;

        tx.commit().await?;
        Ok(())
    }

    #[instrument(
        skip(self, new_event, old_event),
        fields(
            new_declaration_id = %new_event.declaration_id(),
            old_declaration_id = %old_id,
            new_expected_version,
            old_expected_version
        )
    )]
    async fn save_supersede(
        &self,
        new_event: &DeclarationEvent,
        new_expected_version: u64,
        old_id: DeclarationId,
        old_event: &DeclarationEvent,
        old_expected_version: u64,
    ) -> Result<(), RepositoryError> {
        let mut tx = self.pool.begin().await?;
        let new_version =
            i64::try_from(new_expected_version.saturating_add(1)).unwrap_or(i64::MAX);
        let old_version =
            i64::try_from(old_expected_version.saturating_add(1)).unwrap_or(i64::MAX);

        // Insert NEW declaration's Submitted event + projection + outbox.
        insert_event(&mut tx, new_event, new_version).await?;
        upsert_projection_with_supersedes(
            &mut tx,
            new_event,
            new_version,
            Some(old_id.0),
        )
        .await?;
        write_outbox(&mut tx, new_event).await?;

        // Insert OLD declaration's Superseded event + projection update +
        // outbox. (Order is intentional: NEW first so its projection row
        // exists before any reader could observe a stale OLD row that
        // points at it.)
        insert_event(&mut tx, old_event, old_version).await?;
        upsert_projection(&mut tx, old_event, old_version).await?;
        write_outbox(&mut tx, old_event).await?;

        tx.commit().await?;
        Ok(())
    }

    #[instrument(skip(self), fields(declaration_id = %id))]
    async fn load_projection(
        &self,
        id: DeclarationId,
    ) -> Result<Option<DeclarationProjection>, RepositoryError> {
        let row_opt = sqlx::query!(
            r#"
            SELECT declaration_id, entity_id, declarant_principal, declarant_role,
                   declaration_kind, effective_from, beneficial_owners, attestation,
                   state, aggregate_version, submitted_at, receipt_hash_hex,
                   correlation_id, verification_state, verification_lane,
                   verification_case_id, verified_at,
                   supersedes_declaration_id, superseded_by_declaration_id, superseded_at,
                   metadata_notes, amended_at, corrected_at
            FROM declarations
            WHERE declaration_id = $1
            "#,
            id.0,
        )
        .fetch_optional(&self.pool)
        .await?;

        let Some(row) = row_opt else {
            return Ok(None);
        };

        let verification_lane = match row.verification_lane.as_deref() {
            None => None,
            Some(v) => Some(parse_lane(v)?),
        };

        Ok(Some(DeclarationProjection {
            declaration_id: DeclarationId(row.declaration_id),
            entity_id: EntityId(row.entity_id),
            declarant_principal: row.declarant_principal,
            declarant_role: parse_declarant_role(&row.declarant_role)?,
            kind: parse_kind(&row.declaration_kind)?,
            effective_from: row.effective_from,
            beneficial_owners: serde_json::from_value(row.beneficial_owners)?,
            attestation: serde_json::from_value::<CryptographicAttestation>(row.attestation)?,
            state: parse_state(&row.state)?,
            version: u64::try_from(row.aggregate_version).unwrap_or(0),
            submitted_at: row.submitted_at,
            receipt_hash_hex: row.receipt_hash_hex,
            correlation_id: row.correlation_id,
            supersedes_declaration_id: row.supersedes_declaration_id.map(DeclarationId),
            superseded_by_declaration_id: row.superseded_by_declaration_id.map(DeclarationId),
            superseded_at: row.superseded_at,
            verification_state: row.verification_state,
            verification_lane,
            verification_case_id: row.verification_case_id,
            verified_at: row.verified_at,
            metadata_notes: row.metadata_notes,
            amended_at: row.amended_at,
            corrected_at: row.corrected_at,
        }))
    }

    #[instrument(skip(self, principal))]
    async fn find_by_principal(
        &self,
        principal: &str,
    ) -> Result<Vec<DeclarationProjection>, RepositoryError> {
        // Strict match by declarant_principal. Returns every declaration
        // submitted by this authenticated subject across the full
        // history (including superseded rows — D15 says the audit chain
        // is the source of truth; the declarant has the right to see
        // their full record).
        //
        // Ordering: submitted_at DESC so the declarant sees their most
        // recent activity first. `idx_declarations_state` does not cover
        // this lookup; for v1 traffic volumes the table-scan cost is
        // bounded by per-principal row count (typically O(10)). If
        // sustained traffic grows we'll add `idx_declarations_principal`
        // in a follow-up migration.
        let rows = sqlx::query!(
            r#"
            SELECT declaration_id, entity_id, declarant_principal, declarant_role,
                   declaration_kind, effective_from, beneficial_owners, attestation,
                   state, aggregate_version, submitted_at, receipt_hash_hex,
                   correlation_id, verification_state, verification_lane,
                   verification_case_id, verified_at,
                   supersedes_declaration_id, superseded_by_declaration_id, superseded_at,
                   metadata_notes, amended_at, corrected_at
            FROM declarations
            WHERE declarant_principal = $1
            ORDER BY submitted_at DESC
            "#,
            principal,
        )
        .fetch_all(&self.pool)
        .await?;

        let mut out = Vec::with_capacity(rows.len());
        for row in rows {
            let verification_lane = match row.verification_lane.as_deref() {
                None => None,
                Some(v) => Some(parse_lane(v)?),
            };
            out.push(DeclarationProjection {
                declaration_id: DeclarationId(row.declaration_id),
                entity_id: EntityId(row.entity_id),
                declarant_principal: row.declarant_principal,
                declarant_role: parse_declarant_role(&row.declarant_role)?,
                kind: parse_kind(&row.declaration_kind)?,
                effective_from: row.effective_from,
                beneficial_owners: serde_json::from_value(row.beneficial_owners)?,
                attestation: serde_json::from_value::<CryptographicAttestation>(row.attestation)?,
                state: parse_state(&row.state)?,
                version: u64::try_from(row.aggregate_version).unwrap_or(0),
                submitted_at: row.submitted_at,
                receipt_hash_hex: row.receipt_hash_hex,
                correlation_id: row.correlation_id,
                supersedes_declaration_id: row.supersedes_declaration_id.map(DeclarationId),
                superseded_by_declaration_id: row.superseded_by_declaration_id.map(DeclarationId),
                superseded_at: row.superseded_at,
                verification_state: row.verification_state,
                verification_lane,
                verification_case_id: row.verification_case_id,
                verified_at: row.verified_at,
                metadata_notes: row.metadata_notes,
                amended_at: row.amended_at,
                corrected_at: row.corrected_at,
            });
        }
        Ok(out)
    }
}

fn parse_lane(s: &str) -> Result<VerificationLane, RepositoryError> {
    match s {
        "green" => Ok(VerificationLane::Green),
        "yellow" => Ok(VerificationLane::Yellow),
        "red" => Ok(VerificationLane::Red),
        other => Err(RepositoryError::Backend(sqlx::Error::Decode(
            format!("unknown verification_lane: {other}").into(),
        ))),
    }
}

fn parse_declarant_role(s: &str) -> Result<DeclarantRole, RepositoryError> {
    match s {
        "self" => Ok(DeclarantRole::SelfDeclaration),
        "authorised_agent" => Ok(DeclarantRole::AuthorisedAgent),
        "operator_assisted" => Ok(DeclarantRole::OperatorAssisted),
        other => Err(RepositoryError::Backend(sqlx::Error::Decode(
            format!("unknown declarant_role: {other}").into(),
        ))),
    }
}

fn parse_kind(s: &str) -> Result<DeclarationKind, RepositoryError> {
    match s {
        "incorporation" => Ok(DeclarationKind::Incorporation),
        "annual_renewal" => Ok(DeclarationKind::AnnualRenewal),
        "change_of_control" => Ok(DeclarationKind::ChangeOfControl),
        "correction" => Ok(DeclarationKind::Correction),
        "amendment" => Ok(DeclarationKind::Amendment),
        other => Err(RepositoryError::Backend(sqlx::Error::Decode(
            format!("unknown declaration_kind: {other}").into(),
        ))),
    }
}

fn parse_state(s: &str) -> Result<DeclarationState, RepositoryError> {
    match s {
        "draft" => Ok(DeclarationState::Draft),
        "submitted" => Ok(DeclarationState::Submitted),
        "in_verification" => Ok(DeclarationState::InVerification),
        "accepted" => Ok(DeclarationState::Accepted),
        "rejected" => Ok(DeclarationState::Rejected),
        "superseded" => Ok(DeclarationState::Superseded),
        other => Err(RepositoryError::Backend(sqlx::Error::Decode(
            format!("unknown declaration state: {other}").into(),
        ))),
    }
}

fn decode_event(
    event_type: &str,
    payload: JsonValue,
) -> Result<DeclarationEvent, RepositoryError> {
    match event_type {
        "declaration.submitted.v1" => {
            let v1: DeclarationSubmittedV1 = serde_json::from_value(payload)?;
            Ok(DeclarationEvent::Submitted(v1))
        }
        "declaration.verified.v1" => {
            let v1: DeclarationVerifiedV1 = serde_json::from_value(payload)?;
            Ok(DeclarationEvent::Verified(v1))
        }
        "declaration.superseded.v1" => {
            let v1: DeclarationSupersededV1 = serde_json::from_value(payload)?;
            Ok(DeclarationEvent::Superseded(v1))
        }
        "declaration.amended.v1" => {
            let v1: DeclarationAmendedV1 = serde_json::from_value(payload)?;
            Ok(DeclarationEvent::Amended(v1))
        }
        "declaration.corrected.v1" => {
            let v1: DeclarationCorrectedV1 = serde_json::from_value(payload)?;
            Ok(DeclarationEvent::Corrected(v1))
        }
        other => Err(RepositoryError::Backend(sqlx::Error::Decode(
            format!("unknown event_type: {other}").into(),
        ))),
    }
}

async fn insert_event(
    tx: &mut Transaction<'_, Postgres>,
    event: &DeclarationEvent,
    new_version: i64,
) -> Result<(), RepositoryError> {
    let (declaration_id, correlation_id, payload) = match event {
        DeclarationEvent::Submitted(p) => {
            (p.declaration_id.0, p.correlation_id, serde_json::to_value(p)?)
        }
        DeclarationEvent::Verified(p) => {
            // No declarant-supplied correlation_id on a verified event;
            // tracing context still flows via the request span. Stamp
            // the case_id so the event row carries its provenance.
            (p.declaration_id.0, p.verification_case_id, serde_json::to_value(p)?)
        }
        DeclarationEvent::Superseded(p) => {
            (p.declaration_id.0, p.correlation_id, serde_json::to_value(p)?)
        }
        DeclarationEvent::Amended(p) => {
            (p.declaration_id.0, p.correlation_id, serde_json::to_value(p)?)
        }
        DeclarationEvent::Corrected(p) => {
            (p.declaration_id.0, p.correlation_id, serde_json::to_value(p)?)
        }
    };
    let event_type = event.event_type();
    let result = sqlx::query!(
        r#"
        INSERT INTO declaration_events
            (declaration_id, aggregate_version, event_type, event_payload, correlation_id, causation_id)
        VALUES ($1, $2, $3, $4, $5, NULL)
        "#,
        declaration_id,
        new_version,
        event_type,
        payload,
        correlation_id,
    )
    .execute(&mut **tx)
    .await;

    match result {
        Ok(_) => Ok(()),
        Err(sqlx::Error::Database(db_err)) if db_err.is_unique_violation() => {
            Err(RepositoryError::Conflict {
                expected: u64::try_from(new_version - 1).unwrap_or(0),
                found: u64::try_from(new_version).unwrap_or(0),
            })
        }
        Err(e) => Err(RepositoryError::Backend(e)),
    }
}

/// Wraps `upsert_projection` for the supersede path so the new
/// declaration's row carries the `supersedes_declaration_id` pointer.
/// For non-Submitted events the `supersedes` arg is ignored.
async fn upsert_projection_with_supersedes(
    tx: &mut Transaction<'_, Postgres>,
    event: &DeclarationEvent,
    new_version: i64,
    supersedes: Option<uuid::Uuid>,
) -> Result<(), RepositoryError> {
    match event {
        DeclarationEvent::Submitted(p) => {
            let owners = serde_json::to_value(&p.beneficial_owners)?;
            let attestation = serde_json::to_value(&p.attestation)?;
            let declarant_role = p.declarant_role.as_str();
            let kind = p.kind.as_str();
            sqlx::query!(
                r#"
                INSERT INTO declarations (
                    declaration_id, entity_id, declarant_principal, declarant_role,
                    declaration_kind, effective_from, beneficial_owners, attestation,
                    state, aggregate_version, submitted_at, receipt_hash_hex, correlation_id,
                    verification_state, supersedes_declaration_id
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
                ON CONFLICT (declaration_id) DO UPDATE SET
                    state             = EXCLUDED.state,
                    aggregate_version = EXCLUDED.aggregate_version,
                    updated_at        = NOW()
                "#,
                p.declaration_id.0,
                p.entity_id.0,
                p.declarant_principal,
                declarant_role,
                kind,
                p.effective_from,
                owners,
                attestation,
                "submitted",
                new_version,
                p.submitted_at,
                p.receipt_hash_hex,
                p.correlation_id,
                "pending",
                supersedes,
            )
            .execute(&mut **tx)
            .await?;
            Ok(())
        }
        _ => upsert_projection(tx, event, new_version).await,
    }
}

async fn upsert_projection(
    tx: &mut Transaction<'_, Postgres>,
    event: &DeclarationEvent,
    new_version: i64,
) -> Result<(), RepositoryError> {
    match event {
        DeclarationEvent::Submitted(p) => {
            let owners = serde_json::to_value(&p.beneficial_owners)?;
            let attestation = serde_json::to_value(&p.attestation)?;
            let declarant_role = p.declarant_role.as_str();
            let kind = p.kind.as_str();
            sqlx::query!(
                r#"
                INSERT INTO declarations (
                    declaration_id, entity_id, declarant_principal, declarant_role,
                    declaration_kind, effective_from, beneficial_owners, attestation,
                    state, aggregate_version, submitted_at, receipt_hash_hex, correlation_id,
                    verification_state
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
                ON CONFLICT (declaration_id) DO UPDATE SET
                    state             = EXCLUDED.state,
                    aggregate_version = EXCLUDED.aggregate_version,
                    updated_at        = NOW()
                "#,
                p.declaration_id.0,
                p.entity_id.0,
                p.declarant_principal,
                declarant_role,
                kind,
                p.effective_from,
                owners,
                attestation,
                "submitted",
                new_version,
                p.submitted_at,
                p.receipt_hash_hex,
                p.correlation_id,
                "pending",
            )
            .execute(&mut **tx)
            .await?;
        }
        DeclarationEvent::Verified(p) => {
            // Projection-only update; the declarations row already exists
            // from the prior Submitted event. The aggregate's `state`
            // column AND the `verification_state` mirror are written in
            // the same statement so reads see a consistent snapshot.
            let state_str = p.lane.to_declaration_state().as_str();
            let verification_state_str = p.lane.as_verification_state_str();
            let lane_str = p.lane.as_str();
            sqlx::query!(
                r#"
                UPDATE declarations
                SET state               = $2,
                    aggregate_version   = $3,
                    verification_state  = $4,
                    verification_lane   = $5,
                    verification_case_id = $6,
                    verified_at         = $7,
                    updated_at          = NOW()
                WHERE declaration_id = $1
                "#,
                p.declaration_id.0,
                state_str,
                new_version,
                verification_state_str,
                lane_str,
                p.verification_case_id,
                p.completed_at,
            )
            .execute(&mut **tx)
            .await?;
        }
        DeclarationEvent::Superseded(p) => {
            sqlx::query!(
                r#"
                UPDATE declarations
                SET state                        = 'superseded',
                    aggregate_version            = $2,
                    superseded_by_declaration_id = $3,
                    superseded_at                = $4,
                    updated_at                   = NOW()
                WHERE declaration_id = $1
                "#,
                p.declaration_id.0,
                new_version,
                p.superseded_by_declaration_id.0,
                p.superseded_at,
            )
            .execute(&mut **tx)
            .await?;
        }
        DeclarationEvent::Amended(p) => {
            // Re-project the amended fields in place. State is
            // unchanged (Submitted or InVerification per the
            // aggregate's invariant); aggregate_version advances; the
            // amended_at timestamp captures when the amendment landed.
            let owners = serde_json::to_value(&p.after.beneficial_owners)?;
            let role = p.after.declarant_role.as_str();
            sqlx::query!(
                r#"
                UPDATE declarations
                SET beneficial_owners = $2,
                    effective_from    = $3,
                    declarant_role    = $4,
                    aggregate_version = $5,
                    amended_at        = $6,
                    updated_at        = NOW()
                WHERE declaration_id = $1
                "#,
                p.declaration_id.0,
                owners,
                p.after.effective_from,
                role,
                new_version,
                p.amended_at,
            )
            .execute(&mut **tx)
            .await?;
        }
        DeclarationEvent::Corrected(p) => {
            // Update metadata only; canonical declaration payload is
            // unchanged. Aggregate state stays Submitted.
            sqlx::query!(
                r#"
                UPDATE declarations
                SET metadata_notes    = $2,
                    aggregate_version = $3,
                    corrected_at      = $4,
                    updated_at        = NOW()
                WHERE declaration_id = $1
                "#,
                p.declaration_id.0,
                p.after.metadata_notes.as_deref(),
                new_version,
                p.corrected_at,
            )
            .execute(&mut **tx)
            .await?;
        }
    }
    Ok(())
}

async fn write_outbox(
    tx: &mut Transaction<'_, Postgres>,
    event: &DeclarationEvent,
) -> Result<(), RepositoryError> {
    let (declaration_id, payload) = match event {
        DeclarationEvent::Submitted(p) => (p.declaration_id.0, serde_json::to_value(p)?),
        DeclarationEvent::Verified(p) => (p.declaration_id.0, serde_json::to_value(p)?),
        DeclarationEvent::Superseded(p) => (p.declaration_id.0, serde_json::to_value(p)?),
        DeclarationEvent::Amended(p) => (p.declaration_id.0, serde_json::to_value(p)?),
        DeclarationEvent::Corrected(p) => (p.declaration_id.0, serde_json::to_value(p)?),
    };
    let event_id = uuid::Uuid::now_v7();
    let event_type = event.event_type();
    let partition_key = declaration_id.to_string();
    sqlx::query!(
        r#"
        INSERT INTO outbox (
            event_id, event_type, event_version, aggregate_type, aggregate_id,
            partition_key, payload
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        "#,
        event_id,
        event_type,
        1_i32,
        "declaration",
        declaration_id,
        partition_key,
        payload,
    )
    .execute(&mut **tx)
    .await?;
    Ok(())
}

// Helper for the API layer / idempotency middleware.
pub struct IdempotencyStore {
    pool: PgPool,
}

#[derive(Debug, Clone)]
pub struct IdempotencyRecord {
    pub response_status: i16,
    pub response_body: JsonValue,
    pub request_hash: String,
}

impl IdempotencyStore {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Expose the underlying pool to the readiness probe.
    pub fn pool(&self) -> &PgPool {
        &self.pool
    }

    /// Look up an existing idempotency record without mutating state.
    pub async fn check_existing(
        &self,
        idempotency_key: &str,
        declarant_principal: &str,
    ) -> Result<Option<IdempotencyRecord>, sqlx::Error> {
        let row_opt = sqlx::query!(
            r#"
            SELECT response_status, response_body, request_hash
            FROM idempotency_records
            WHERE idempotency_key = $1
              AND declarant_principal = $2
              AND expires_at > NOW()
            "#,
            idempotency_key,
            declarant_principal,
        )
        .fetch_optional(&self.pool)
        .await?;
        Ok(row_opt.map(|row| IdempotencyRecord {
            response_status: row.response_status,
            response_body: row.response_body,
            request_hash: row.request_hash,
        }))
    }

    /// Record a fresh idempotency entry.
    pub async fn record(
        &self,
        idempotency_key: &str,
        declarant_principal: &str,
        request_hash: &str,
        response_status: i16,
        response_body: &JsonValue,
        ttl_seconds: i64,
    ) -> Result<(), sqlx::Error> {
        let ttl_seconds_f64 = ttl_seconds as f64;
        sqlx::query!(
            r#"
            INSERT INTO idempotency_records
                (idempotency_key, declarant_principal, request_hash,
                 response_status, response_body, expires_at)
            VALUES ($1, $2, $3, $4, $5,
                    NOW() + (CAST($6 AS DOUBLE PRECISION) * INTERVAL '1 second'))
            ON CONFLICT (idempotency_key) DO NOTHING
            "#,
            idempotency_key,
            declarant_principal,
            request_hash,
            response_status,
            response_body,
            ttl_seconds_f64,
        )
        .execute(&self.pool)
        .await?;
        Ok(())
    }
}

#[derive(Debug, thiserror::Error)]
pub enum AdapterError {
    #[error(transparent)]
    Sqlx(#[from] sqlx::Error),
    #[error("invalid stored data: {0}")]
    InvalidData(String),
}

// Suppress unused-import warning during the partial-build phase.
#[allow(dead_code)]
fn _force_imports(_o: BeneficialOwnerClaim) {}
